import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Experimental_CssVarsProvider as CssVarsProvider } from '@mui/material/styles';
import { experimental_extendTheme as extendTheme } from '@mui/material/styles';
import { ThemeProvider, createTheme } from '@mui/material/styles';


import { ColorModeProvider } from '@/app/theme_no_cssvar';

import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Container from '@mui/material/Container';

import AppShell from '@/components/app-shell';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ColorModeProvider>
            <CssBaseline />
            
            <Box sx={{ display: 'flex' }}>


              <AppShell />

              <Box
                component="main"
                sx={{
                  // backgroundColor: 'grey',
                  // backgroundColor: (theme) =>
                  //   theme.palette.mode === 'light'
                  //     ? theme.palette.grey[100]
                  //     : theme.palette.grey[900],
                  flexGrow: 1,
                  height: '100vh',
                  overflow: 'auto',
                }}
              >
                <Toolbar />
                <Container maxWidth="lg" sx={{ mt: 4, mb: 4 }}>
                  {children}
                </Container>
              </Box>
            </Box>
          </ColorModeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
